### ISSUE TITLE
Undefined class 

### ISSUE THREAD

**Issue by alekln** [ItellaPlugins/itella-api#11]
Wordpress version 5.8.2

Triggering / pressing button "Registrer shipment" causes

`[19-Apr-2022 08:34:28 UTC] PHP Fatal error:  Uncaught Error: Class 'Pakettikauppa\Shipment\Sender' not found in /var/www/html/wp-content/plugins/itella-shipping-woocommerce-master/libs/itella-api/src/Shipment/Party.php:57 Stack trace: #0 /var/www/html/wp-content/plugins/itella-shipping-woocommerce-master/admin/class-itella-shipping-method.php(1964): Mijora\Itella\Shipment\Party->__construct() #1 /var/www/html/wp-content/plugins/itella-shipping-woocommerce-master/admin/class-itella-shipping-method.php(1633): Itella_Shipping_Method->create_sender() #2 /var/www/html/wp-content/plugins/itella-shipping-woocommerce-master/admin/class-itella-shipping-method.php(1739): Itella_Shipping_Method->itella_post_shipment_actions() #3 /var/www/html/wp-includes/class-wp-hook.php(303): Itella_Shipping_Method->itella_ajax_single_register_shipment() #4 /var/www/html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() #5 /var/www/html/wp-includes/plugin.php(470): WP_Hook->do_action() #6 /var/www/h in /var/www/html/wp-content/plugins/itella-shipping-woocommerce-master/libs/itella-api/src/Shipment/Party.php on line 57`

https://github.com/ItellaPlugins/itella-api/blob/f6e5f2bac8956be39061e8dfc2269f3c9e61ada6/src/Shipment/Party.php#L57

**Comment by markakk** [comment]
Hello,

In Itella API library everything looks good. Also Woocommerce plugin working good for us, when we press "Register shipment" button. We have not received any more complaints from Itella clients about this. It seems that the problem is only for you.
Please check if you have an _autoload.php_ file with libraries in the `itella-shipping/libs/itella-api/vendor` folder.
